# Attention

In [1]:
import torch

/Users/yousefnami/Desktop/Main/2.Personal/MyStuff/2.Extracurriculars/Coding/DataScience/Repositories/nlplorer/venv/lib/python3.13/site-packages/torch/_subclasses/functional_tensor.py:307: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [11]:
def attention(embedding_matrix: torch.Tensor, query_matrix: torch.Tensor, key_matrix: torch.Tensor, value_matrix: torch.Tensor) -> torch.Tensor:
    # -- value matrix has to map back to embeddings..!
    Q = torch.matmul(embedding_matrix, query_matrix)  # shape: batch_size x attention_dim
    K = torch.matmul(embedding_matrix, key_matrix)    # shape: batch_size x attention_dim)
    attention_scores = torch.matmul(Q, K.T) / (query_matrix.shape[0] ** (0.5))  # shape: batch_size x batch_size
    # each row represents the query of a token against all the keys including itself
    # -- we set the upper triangular to neg infinity to preventing attending of future tokens
    upper_triangular_mask = torch.triu_indices(attention_scores.shape[0], attention_scores.shape[1], offset=1) 
    attention_scores[upper_triangular_mask[0], upper_triangular_mask[1]] = - torch.inf
    print(attention_scores)
    attention_weights = torch.softmax(attention_scores, dim=1)
    print(attention_weights)
    context_vectors = torch.matmul(attention_weights, value_matrix)

    return context_vectors



In [16]:
EMBEDDING_DIM = 4
ATTENTION_DIM = 2
VOCAB_SIZE = 3

embedding_matrix = torch.randn(VOCAB_SIZE, EMBEDDING_DIM)  # shape: batch_size x embedding_dim
query_matrix = torch.randn(EMBEDDING_DIM, ATTENTION_DIM)  # shape: embedding_dim x attention_dim
key_matrix = torch.randn(EMBEDDING_DIM, ATTENTION_DIM)    # shape
value_matrix = torch.randn(VOCAB_SIZE, EMBEDDING_DIM)  # shape: embedding_dim x attention_dim


attention(embedding_matrix, query_matrix, key_matrix, value_matrix)

tensor([[-0.5660,    -inf,    -inf],
        [-0.9616, -0.0282,    -inf],
        [-0.1591, -0.0394,  1.1593]])
tensor([[1.0000, 0.0000, 0.0000],
        [0.2822, 0.7178, 0.0000],
        [0.1705, 0.1922, 0.6373]])


tensor([[-1.4660,  0.7784,  0.4411, -0.1402],
        [ 0.6515,  0.0486, -0.5548, -0.0112],
        [-0.2571, -0.1282,  1.3138, -0.0211]])